### ISSUE TITLE
Create read-only version of shrugger for use on dev, test, prod.

### ISSUE THREAD

**Issue by owenmorrill** [CuBoulder/lil_shrugger#138]
No switching environments. Only be able to read/work/whatnot on the server you're currently on.

**Comment by owenmorrill** [comment]
afinnarn
[11:12 AM] 
I think you really want to get https://github.com/CuBoulder/lil_shrugger/blob/dev/src/config/config.js#L137 working instead of changing the actual code to one implementation. Then, just make sure that if there is only one atlas/Express environment no selector shows up. Auth is blank/null, then don't include...etc.
GitHub
CuBoulder/lil_shrugger
lil_shrugger - Atlas' Best Friend
[11:13] 
now back to my carb-laden buffet binge
[11:14] 
...I think you just need to append the JS file to the document to "read" the contents

**Comment by alexfinnarn** [comment]
The environment selector can now be eliminated via a config file include; however, there is no access control for running commands, adding/editing code, or adding/editing sites. 

I think adding an exclude or "off" switch for displaying those controls makes sense. The `store` object would have an array with keys to exclude named after the buttons that would be hidden. 

```
store: {
  state: {
    blockAccess: ['row:Edit', 'siteCreateButton:Create-A-Site']
  }
}
```

If roles were added, then you'd want to expand that array to include an object for each role and then a step to check the user role before displaying the parts of the application that can be edited.
