### ISSUE TITLE
No emails in user export on http://live-shrugger-8.pantheonsite.io/shrugger/

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/lil_shrugger#204]
I get users when I export from shurgger on my copy running on express.local, but export from http://live-shrugger-8.pantheonsite.io/shrugger/ is empty.

**Comment by alexfinnarn** [comment]
After pushing up v0.2.4 to Pantheon, the emails appear to be exporting for me. A help icon has been added with some instructions about how to navigate the Sites page including the options for the email export.

**Comment by alexfinnarn** [comment]
closing as fixed for now.
