### ISSUE TITLE
Add new environment

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/lil_shrugger#279]
https://osr-dev-atlas01.int.colorado.edu/atlas

**Comment by alexfinnarn** [comment]
I added a "NewDev" endpoint but I still get a CORS issue for https://osr-dev-atlas01.int.colorado.edu/atlas/commands. All of the other endpoints return the same data I expected.

**Comment by jwfuller** [comment]
Other environments are osr-test-atlas01.int.colorado.edu/atlas and osr-prod-atlas01.int.colorado.edu/atlas
