### ISSUE TITLE
Patching a code record sends the patch to a site record.

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/lil_shrugger#285]
1. Find a code record
2. Update commit hash
3. Patch is sent to a site record with the same id as the code record

Error in Atlas Request:
Status Code: 404
Text: NOT FOUND
URL: https://osr-atlas03.int.colorado.edu/atlas/sites/5a1d8c7d926f5b102cbe3939

You have sent a PATCH request to a site record. Site ID: 5a1d8c7d926f5b102cbe3939

**Comment by alexfinnarn** [comment]
This was a typo already fixed in https://github.com/CuBoulder/lil_shrugger/commit/fcd92743544a8efae3c9d3993891ce71115c50ce#diff-4aa24168a5499ec9b673427d10939fb8
