### ISSUE TITLE
Summary view of how many people are in a given role per site

### ISSUE THREAD

**Issue by jbertrand** [CuBoulder/lil_shrugger#296]
I would like to have a way to see how many people are in a given role for each site. I do not necessarily need to see the names or identikeys, I just want to see how many people are assigned to particular role. 

**For example**
UMC: site owners = 5; content editors = 3; edit my own= 2

**Comment by alexfinnarn** [comment]
I think this would most easily done with an added key to the data table. In the stats, there is now a count of certain roles/users.

```json
  "users": {
    "username": {
      "edit_my_content": [
        "osr-test-edit-own"
      ],
      "content_editor": [
        "osr-test-content",
        "krlu2891",
        "nowa3261"
      ],
      "site_contact": [
        "osr-test-owner",
        "bonneyl"
      ]
    },
    "counts": {
      "edit_my_content": 1,
      "content_editor": 3,
      "site_contact": 2
    },
    "email_address": {
      "edit_my_content": [
        "osr-test-edit-own@colorado.edu"
      ],
      "content_editor": [
        "osr-test-content@colorado.edu",
        "Kristin.Lueck@Colorado.EDU",
        "nonie.roberts@Colorado.EDU"
      ],
      "site_contact": [
        "osr-test-owner@colorado.edu",
        "laura.bonney@Colorado.EDU"
      ]
    }
  },
```

Add `counts` to https://github.com/CuBoulder/lil_shrugger/blob/1.x/src/vuex/store.js#L102 and it would show up in the table as an object. 

As a follow-up, each column could have associated formatting functions included as an option. I'm not sure the best way to accomplish that though without a full report builder functionality. Providing a .csv and help with Excel formulas is probably a way better use of time than trying out a lot of data manipulation for derivative stats. That's what Excel is good at.

**Comment by alexfinnarn** [comment]
merged
