### ISSUE TITLE
Update expressUserRoles To Current Express Roles

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/lil_shrugger#301]
https://github.com/CuBoulder/atlas/blob/master/atlas/data_structure.py can be parsed to get the schemas needed to add for display in the data table.

As far as defaults go, you could start out with the first few keys of the schema.

Use the master branch of Atlas instead of dev.

**Comment by ekellagher** [comment]
Please update Lil shrugger reports to reflect the new user roles in June 2018
