### ISSUE TITLE
Add new roles to email export

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/lil_shrugger#350]
Related to https://github.com/CuBoulder/express/issues/2291

**Comment by alexfinnarn** [comment]
https://github.com/CuBoulder/express/blob/dev/modules/custom/atlas/atlas_statistics/atlas_statistics.inc#L65 really needs to change to reflect the actual role name. With the way MongoDB works, I think you'd have orphaned data in the users/emails arrays.

However, I and others have been confused as to what "site_contact" means but the code clearly maps it to site_owner.

**Comment by alexfinnarn** [comment]
I think this is fixed based on the commit.
