### ISSUE TITLE
Update to support new `drush` endpoint

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/lil_shrugger#352]
The `commands` endpoint has been split into two `command` and `drush`
 `drush` (edited)

Sample payload for POST to `/atlas/drush` to create a drush command
```json
{
    "commands": ["drush cc all","drush updb -y"],
    "query": "\u007B\u0022type\u0022\u003a\u0022express\u0022\u002c\u0022f5only\u0022\u003afalse\u007d"
}
```
To execute the command POST to `/drush/[_id]/execute`

The `commands` endpoint still exists and provides a list `/atlas/commands`

Current list 

```json
{
  "commands": [
    {
      "machine_name": "clear_php_cache", 
      "description": "Clear the PHP script cache on all webservers."
    }, 
    {
      "machine_name": "import_code", 
      "description": "Import code from another Atlas instance. When running the command include the target environment (dev, test, prod) as a payload in the format `{\"env\":\"dev\"}`."
    }, 
    {
      "machine_name": "rebalance_update_groups", 
      "description": "Resort the members of groups 0-10 so that they are evenly distributed."
    }, 
    {
      "machine_name": "update_settings_files", 
      "description": "Update the Drupal settings file."
    }, 
    {
      "machine_name": "update_homepage_files", 
      "description": "Update `.htaccess` and `robots.txt` files"
    }, 
    {
      "machine_name": "heal_code", 
      "description": "Check that all code is present and on the correct hash. Fix any that are not."
    }, 
    {
      "machine_name": "heal_instances", 
      "description": "Checl that all intances are present and the directory structure is correct. Fix any instances that are irregular."
    }
  ]
}
```

To run a command POST to `/commands/[machine_name]`

**Comment by alexfinnarn** [comment]
This issue will probably have multiple branches associated with it. 

To start out, the `drush` endpoint is updated on https://osr-prod-util01.int.colorado.edu/atlas/drush with the schema of https://github.com/CuBoulder/atlas/blob/dev/atlas/data_structure.py#L843

I will start out by adding a Drush command to the Atlas instance. I'm not sure the commands list needs to be separated out, but rather add a "type" property to the command concept in lil_shrugger. Then, you just use the type for any differences in running drush vs commands.

**Comment by alexfinnarn** [comment]
To test:

1. Look at https://osr-test-util01.int.colorado.edu/atlas/drush and the commands. Pick one that you want to use. I'll use a "Clear Cache" command for this example.

2. Modify the query via Postman to be one that is not path based. An example of `{"type":"express"}` is posted below. I use Postman to do this.

```json
{
  "query": "\u007B\u0022type\u0022\u003a\u0022express\u0022\u007d"
}
```

3. Make sure you have "newTest" selected from the environment selector. Choose your command in the Shrugger Command component. You should see the command object listed under "Command Object". If the query doesn't have `"query": "{\"type\":\"express\"}"` then you need to refresh the page using the refresh action icon or reloading the app.

4. Click "Send Command" in the Command component and see that you get a warning message like:
 
```
You are about to send the "Clear Cache" command to this MongoDB query: {"type":"express"}....
```

5. Click "Fire!" to execute the command. You should see a message about the command being executed three seconds later.

6. Look in Kibana for the commands running. I'm not sure the link is right, but it does show stuff...

7. Choose your command again, but this time select some sites from the DataTable component.

8. Click "Send Command" and you should see a message like:

```
You are about to send the "Clear Cache" command to 2 site(s): "p18b7d52f134","p13a7ef60bf4".

WARNING: You will change the command's query to only execute on these sites by clicking "Fire!" and running the command.
```

9. Click "Fire!", look for the patched and executed messages, and then look in Kibana to see that the commands have run.

**Comment by alexfinnarn** [comment]
This PR takes into account the "drush" endpoint but not "command". I think the command endpoint is now dead...but I'm not sure.

**Comment by jwfuller** [comment]
@alexfinnarn The `command` endpoint is not dead. They are now more like stored procedures that do not use drush. List is here https://github.com/CuBoulder/atlas/blob/dev/atlas/commands.py

Call by `POST` to `/commands/<string:machine_name>`

More command code is here https://github.com/CuBoulder/atlas/blob/dev/run.py#L53

A lot of this is in the description for this issue.

**Comment by alexfinnarn** [comment]
updated in 2.x
