### ISSUE TITLE
Add Validate Message To All Atlas CUD Operations

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/lil_shrugger#372]
Like the Commands validation listeners, the validate event for all the CUD requests to Atlas can be listened to and provide a warning message to users. If you see three messages validating the wrong site/code record, hopefully, the user will reboot the application or follow instructions in the message.

**Comment by alexfinnarn** [comment]
I think it makes sense to also validate update and create requests.

**Comment by alexfinnarn** [comment]
The CreateCode component doesn't use the ConfirmButton at this point, so it is the only CUD operation that doesn't have a warning message in this PR.

**Comment by kreynen** [comment]
Rather than display the mixed site object/stats object that is being displayed in the CUD message now, it would be more helpful to show what's actually going to be sent as the PATCH/POST/DELETE.

**Comment by alexfinnarn** [comment]
The reason the actual request isn't added to the warning message is that it happens akin to a Drupal form submission and is generated too late in the process. It is easy to add what I did, but the whole validation system with the confirm buttons would have to be altered to stop the process after the request is generated but before it is sent out.
