### ISSUE TITLE
Add setting to set the destination query string

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/lil_shrugger#377]
While the ?destination=/admin/people/invite is useful for @jbertrand and @ekellagher, @cathysnider and I are most likely going to admin/reports/status.  It would be useful to be able to change that in the Shrugger settings.  That way if you are doing something like disabling a bundle on several sites, you could temporarily change that value to be admin/config/development/atlas

**Comment by alexfinnarn** [comment]
merged
