### ISSUE TITLE
Use Atlas version vs. different installs to manage schema/endpoint changes

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/lil_shrugger#380]
Rather than chase changes to Atlas by deploying different versions of Atlas to different urls, we need to be able to have 1 shrugger install that can use different versions of code based on the version of Atlas each endpoint is using by looking that up at https://osr-prod-util01.int.colorado.edu/atlas/version.

This is in an extreme state now with old prod and new prod using very different versions of Atlas, but once we're back to 3 environments we don't want to have to update the Shrugger pointed at dev to different branch than the Shugger pointed at prod.

**Comment by alexfinnarn** [comment]
The best way to do this is to create interfaces for exports, commands, and any other Atlas interaction. When the environment indicator is changed, new objects are instantiated that implement the interface depending on the Atlas environment.

**Comment by alexfinnarn** [comment]
Looks like the internet mention TypeScript https://www.typescriptlang.org/docs/handbook/interfaces.html and https://hackernoon.com/implementing-interfaces-in-javascript-with-implement-js-8746838f8caa

**Comment by alexfinnarn** [comment]
I would just build a version on different commit hashes. If you clone tag `1.2.3` into one directory and tag `2.1.5` into another then build/serve that version, you'll have different versions to work with. Netlify builds environments for each PR so that could be used, but running the code locally is ideal.
