### ISSUE TITLE
Use sites/agg to show per environment warnings about things like outdated stats

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/lil_shrugger#382]
![screen shot 2018-06-21 at 4 15 29 pm](https://user-images.githubusercontent.com/385234/41748266-57b08aea-756e-11e8-8506-14731e2c9385.png)

https://osr-atlas01.int.colorado.edu/atlas/sites/agg doesn't have what we'd need to replace the messages flowing into a Slack no one is looking at, but it provides the structure to do this.  Similar to Drupal's site status variable that is triggered by any hook_requirements error, we need something similar for knowing whether there is something wrong with stats before we start taking actions based on the current stats.

The current sites/agg isn't currently cached and these calculations could get expensive so we need to think through how this will work.

**Comment by alexfinnarn** [comment]
All of the stats information passes through a formatting function so checking the date on the most recent version and comparing it to 48 hours ago would allow for an array of sites to be gathered in the store.

I've wanted to add a "Status" page to the app where you would get notices like that as well as health checks of Atlas. Useful exports of Kibana data could also be incorporated...New Relic also has embedded charts. Need to think about access control though.
