### ISSUE TITLE
Changes for new environment

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/lil_shrugger#389]
Fields removed

- [x] `type` (change default site query)
- [x] `f5only`

Environments that exist, desired names and current web URLs

- [x] Dev | www-dev-new.colorado.edu
- [x] Test | www-test-new.colorado.edu
- [x] Prod | www.colorado.edu

**Comment by alexfinnarn** [comment]
changes appear on http://ultimate-shrugger-8.pantheonsite.io/shrugger/

**Comment by jwfuller** [comment]
The removal of these fields is going in to a release that will be deployed between 11/26/18 and 11/30/18

**Comment by jwfuller** [comment]
Looks like this line will also need to be updated https://github.com/CuBoulder/lil_shrugger/blob/1.x/src/pages/Packages.vue#L122

**Comment by alexfinnarn** [comment]
changed the Packages part in the code but that whole thing needs tested to see if it even works.
